services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SERVERURL=$PROXY_SERVER_PUBLIC_URL #optional
      - SERVERPORT=51820 #optional
      - PEERS=proxy #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
      - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./volumes/wireguard/data:/config
    ports:
      # wireguard port
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  proxy-rs:
    profiles: ["tests", "prod"]
    build:
      context: ./
      dockerfile: Dockerfile
    image: omnia/proxy-rs
    container_name: proxy-rs
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    depends_on:
      - wireguard
    restart: unless-stopped
    environment:
      - ENV=$ENV
      - WIREGUARD_CONTAINER_NAME=wireguard
      - OMNIA_BACKEND_CANISTER_URL=$OMNIA_BACKEND_CANISTER_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/proxy/data/wg0.conf:/proxy/wg0.conf
    ports:
      # proxy http port
      - $PROXY_PUBLIC_PORT:8081
